language: php

php:
  - '7.1'

jobs:
  include:
    - stage: publish in TER
      if: tag IS present
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install requirements
            composer global require --dev helhum/ter-client dev-master
            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx
            # Create tag message
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            # Build extension files
            composer extension-release
            # Upload
            echo "Uploading release ${TRAVIS_TAG} to TER"
            /home/travis/.config/composer/vendor/bin/ter-client upload t3fetch . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
